// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzLyHIUY3PDiZSdsQVq6blMf4ouQ988lI',
    appId: '1:819069931080:web:5e2b4e258bdaccf8a1927d',
    messagingSenderId: '819069931080',
    projectId: 'tp1masterai',
    authDomain: 'tp1masterai.firebaseapp.com',
    storageBucket: 'tp1masterai.appspot.com',
    measurementId: 'G-WYJ8BH780Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe3cPWRy8o6vi4VzxwbCwn9npcXUNNt1E',
    appId: '1:819069931080:android:de86a262315750b3a1927d',
    messagingSenderId: '819069931080',
    projectId: 'tp1masterai',
    storageBucket: 'tp1masterai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhJ948rn3C9wsHkO_54SucNz9i8MMv-fo',
    appId: '1:819069931080:ios:de3bdabc8f2f32aaa1927d',
    messagingSenderId: '819069931080',
    projectId: 'tp1masterai',
    storageBucket: 'tp1masterai.appspot.com',
    iosBundleId: 'com.example.tp1MasterAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhJ948rn3C9wsHkO_54SucNz9i8MMv-fo',
    appId: '1:819069931080:ios:de3bdabc8f2f32aaa1927d',
    messagingSenderId: '819069931080',
    projectId: 'tp1masterai',
    storageBucket: 'tp1masterai.appspot.com',
    iosBundleId: 'com.example.tp1MasterAi',
  );
}
